In [1]:
# 1.[簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？
import numpy as np
arr1 = np.zeros((2,3))
print(arr1)
arr2 = np.empty((2,3))
print(arr2)
#empty會建立很接近0的數值, zeros會建立0的數值
#empty必須讓使用者輸入數值，zeros是建立可以使用的0在array

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [2]:
# 2.在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
import numpy as np
a = np.random.rand(2, 3)
print(a)
b = np.array(a,dtype='int32')
print(b)

[[0.73871978 0.09610761 0.63061694]
 [0.0713523  0.68553004 0.87063978]]
[[0 0 0]
 [0 0 0]]


In [3]:
# 3.承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。
import numpy as np
m = 20
n = 40
c = np.random.randint(m,n,(2,3))
print(c)

[[31 35 39]
 [35 30 37]]
