In [1]:
# 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
import numpy as np
a=np.arange(1,12) 
a[(a <= 6) & (a >= 3)] *= -1
print(a)

[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


In [2]:
# 2.試著從一個隨機陣列中，找出比 0.5 大的數有幾個？
a = np.random.rand(3, 6)
print(a)
print(a[a > 0.5].size) 


[[0.05213366 0.17051122 0.47111254 0.1391225  0.76794067 0.29436326]
 [0.6005075  0.8008737  0.60304983 0.4542826  0.98638229 0.39574175]
 [0.82332472 0.81550206 0.36232582 0.98115873 0.03758767 0.43816419]]
8
