In [2]:
#1. [簡答題] 請問下列這三種方法有什麼不同？
import numpy as np

a= np.arange(6).reshape(3,2)
print(a)
print(a.sum())
print(np.sum(a))
print(sum(a))
# a.sum() , np.sum(a) 回傳所有加總的值
# sum(a) 回傳軸的加總後的陣列

[[0 1]
 [2 3]
 [4 5]]
15
15
[6 9]


In [3]:
#2. 請對一個 5x5 的隨機矩陣作正規化的操作。
a = np.random.random((5,5))
print(a)
b = (a-a.min())/(a.max()-a.min())
print(b)


[[0.38278837 0.53474863 0.639049   0.03670872 0.38993243]
 [0.58315307 0.41806747 0.9351822  0.00138395 0.52833883]
 [0.46939326 0.90102624 0.98474902 0.5770056  0.93094547]
 [0.22546956 0.38542748 0.92973146 0.98012222 0.65457308]
 [0.92341368 0.30798359 0.41670437 0.8897332  0.03802183]]
[[0.38785639 0.54238726 0.648452   0.03592233 0.3951213 ]
 [0.59161052 0.42373228 0.94959469 0.         0.53586902]
 [0.47592632 0.91486094 1.         0.58535906 0.94528629]
 [0.22787632 0.39054014 0.94405175 0.99529494 0.6642387 ]
 [0.93762709 0.31178619 0.42234612 0.90337686 0.03725766]]


In [4]:
#3.請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。
a = np.random.randint(1,100,10)
a[a.argmax()] = -1
print(a)


[73  9  3 24 23 43 39 92 -1 37]
