In [1]:
#array1 = np.array([[10, 8], [3, 5]])
#1.運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
import numpy as np
array1 = np.array([[10, 8], [3, 5]])
array2 = np.linalg.inv(array1 )
print( '反矩陣 = \n', array2 )
print('反矩陣乘上原矩陣為單位矩陣:\n',array1.dot(array2))

反矩陣 = 
 [[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
反矩陣乘上原矩陣為單位矩陣:
 [[1. 0.]
 [0. 1.]]


In [2]:
#2.運用上列array計算特徵值、特徵向量?
print('eigenvalues:',np.linalg.eig(array1)[0],sep='\n')
print('eigenvectors:',np.linalg.eig(array1)[1],sep='\n')

eigenvalues:
[13.  2.]
eigenvectors:
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [3]:
#3.運用上列array計算SVD?
u, s, vh = np.linalg.svd(array1)
print(u)
print(s)
print(vh)

[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]]
[13.94721714  1.86417116]
[[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
